on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: run the action
      id: hello
      uses: ./
      with:
        myInput: 'Vamsi Krishna'
    - name: output
      run: |
        echo ${{ steps.hello.output.memory }}
        echo "Successful"
